# arxiv/submission-worker

FROM arxiv/base

WORKDIR /opt/arxiv

ENV LC_ALL en_US.utf8
ENV LANG en_US.utf8

# We're using MariaDB for testing/development, but production is MySQL (for
# now).
RUN yum -y install mariadb-devel

# Add Python consumer and configuration.
RUN pip install pipenv
RUN pipenv install

ADD core/ /opt/arxiv/core/
RUN pipenv install /opt/arxiv/core/

ENV JWT_SECRET "foo"
EXPOSE 8000

#CMD /bin/bash

ENTRYPOINT ["pipenv", "run", "celery", "worker"]
CMD ["-A", "arxiv.submission.worker.worker_app", "--loglevel=INFO", "-E", "--concurrency=2"]
