# arxiv/submission-agent

FROM arxiv/base

WORKDIR /opt/arxiv

ENV LC_ALL en_US.utf8
ENV LANG en_US.utf8

# We're using MariaDB for testing/development, but production is MySQL (for
# now).
RUN yum -y install mariadb-devel

# Add Python consumer and configuration.
RUN pip install pipenv

ENV AWS_ACCESS_KEY_ID ""
ENV AWS_SECRET_ACCESS_KEY ""

ADD core/ /opt/arxiv/core/
ADD Pipfile /opt/arxiv/
RUN pipenv install /opt/arxiv/core/
ADD agent/agent/ /opt/arxiv/agent/

ENV KINESIS_STREAM "SubmissionEvents"
ENV KINESIS_SHARD_ID "0"
ENV KINESIS_START_TYPE "TRIM_HORIZON"
ENV SUBMISSION_AGENT_DATABASE_URI ""
ENV LOGLEVEL 10

ENV JWT_SECRET "foo"

ENTRYPOINT ["pipenv", "run", "python3.6", "-m", "agent.consumer"]
