# arxiv/submission-worker

FROM arxiv/base

WORKDIR /opt/arxiv

ENV LC_ALL en_US.utf8
ENV LANG en_US.utf8

# We're using MariaDB for testing/development, but production is MySQL (for
# now).
RUN yum -y install mariadb-devel

# Add Python consumer and configuration.
RUN pip install pipenv

ADD Pipfile /opt/arxiv/
RUN pipenv install

ADD core/ /opt/arxiv/core/
RUN pipenv install /opt/arxiv/core/
ADD agent/agent/ /opt/arxiv/agent/

ENV JWT_SECRET "foo"
EXPOSE 8000

ENTRYPOINT ["pipenv", "run", "celery", "worker"]
CMD ["-A", "agent.worker.worker_app", "--loglevel=INFO", "-E", "--concurrency=2"]
